name: Feature Request
description: Suggest an idea or enhancement
title: '[Feature Request]: '
labels: ['enhancement']
assignees:
  - Envoy-VC
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.


        **Additional context**
        Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Envoy-VC/react-terminal/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
